run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - gosec

  disable:
    - depguard
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
