// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"workouts_bot/src/bot"
	"workouts_bot/src/config"
	"workouts_bot/src/database"
)

// Injectors from wire.go:

func InitializeBot() (*BotApp, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	string2 := provideBotToken(configConfig)
	databaseConfig := provideDatabaseConfig(configConfig)
	db, err := database.Connect(databaseConfig)
	if err != nil {
		return nil, err
	}
	webhookConfig := provideWebhookConfig(configConfig)
	botBot, err := bot.New(string2, db, webhookConfig)
	if err != nil {
		return nil, err
	}
	botApp := &BotApp{
		Bot: botBot,
		DB:  db,
	}
	return botApp, nil
}

// wire.go:

func provideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

func provideBotToken(cfg *config.Config) string {
	return cfg.BotToken
}

func provideWebhookConfig(cfg *config.Config) *config.WebhookConfig {
	return &cfg.Webhook
}

type BotApp struct {
	Bot *bot.Bot
	DB  *gorm.DB
}
