// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"workouts_bot/src/config"
	"workouts_bot/src/router"
)

// Injectors from wire.go:

func InitializeService() (*ServiceApp, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	serviceApp := NewServiceApp(configConfig)
	return serviceApp, nil
}

// wire.go:

type ServiceApp struct {
	Engine *gin.Engine
	Cfg    *config.Config
}

func NewServiceApp(cfg *config.Config) *ServiceApp {
	return &ServiceApp{
		Cfg:    cfg,
		Engine: router.NewRouter(cfg),
	}
}
